---
language: ruby
sudo: false
cache: bundler
bundler_args: --without benchmarks tools
script:
  - bundle exec rake
  - bundle exec rubocop
rvm:
  - 2.3.0
  - 2.6.2
  - ruby-head
  - jruby-9.2.7.0
  - truffleruby
env:
  global:
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: truffleruby
